### ISSUE TITLE
Separate the demo's from the main library

### ISSUE THREAD

**Issue by spyhunter99** [cjwizard/cjwizard#49]
A suggestion, separate the demo classes into a separate module instead of embedding them in the main library. I can open a PR for this

**Comment by stevesobol** [comment]
Hey Spyhunter!

Rogan turned over the cjwizard library to me a while ago. I have had ZERO time to devote to it, unfortunately, but I need to change that, since I essentially own the project at this point. So, I want to dig in and start helping you with further development of the library. 

There are things we should discuss that don't need to be attached to GitHub issues. I want to go ahead and set up a slack channel for that stuff. Also, of the issues we have open now, let me know what you want me to start work on, because I want to start contributing to the project next week.

I also registered **cjwizard.com** and at some point I'd like to put a website there, but that's a REALLY low priority at the moment.

Please let me know how I can help!

**Comment by spyhunter99** [comment]
Sweet, you can always use maven to create the site. It's quite easy and i can do a pr for it too if you like. Let me work through a few issues on my end and get back to you

**Comment by stevesobol** [comment]
Maven's great for doing a quick informational site. I won't be using Maven, though, as I want to do a fancier site (common branding with some other dev tools I'm working on, etc) - plus, I'm a web developer and want to add this new site to my portfolio. :) I'm steve at LobosStudios.com - drop me an email when you are ready. Looking forward to working with everyone. :)

**Comment by stevesobol** [comment]
This is essentially the same issue as #39 - I'm going to close this issue and work on that one

**Comment by spyhunter99** [comment]
it isn't but i think some of the previous prs have squashed this. i'll redo it

**Comment by stevesobol** [comment]
Well, I'll reopen this one then, but I'm confused as to what the differences are.

**Comment by spyhunter99** [comment]
ehh i guess they are duplicates, both are covered by the open pr

**Comment by stevesobol** [comment]
OK. That means I can go ahead and close this issue and just work on that one, then?
